# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: environments/.*-secrets\.yaml$
    age: 
      - age1v4c7swg62yzl5wse5eahytxcjyjz85sj2wcw94d266ke7s2tndzs2kugsy
